#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local fnm_namerd="namerd-${NAMERD_VERSION}-exec"
  local url_namerd="https://github.com/BuoyantIO/linkerd/releases/download/${NAMERD_VERSION}/$fnm_namerd"

  cache curl "$fnm_namerd" "$url_namerd"

  mkdir -p "$shome/vendor"

  rsync -ia "${BASEBOX_CACHE}/curl/$fnm_namerd" "$shome/vendor/"
  chmod 755 "$shome/vendor/$fnm_namerd"
  ln -nfs "../vendor/$fnm_namerd" "$shome/bin/namerd"
}

bootstrap
