#!/usr/bin/env bash

function _namerd_profile {
  local shome="${_namerd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  NAMERD_VERSION='1.2.0'
  NAMERCTL_VERSION='0.8.6'
}

_namerd_profile
