#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_namerd="$(basename "$(readlink "$shome/bin/namerd")" | cut -d- -f2)"
  local ver_namerctl="$(basename "$(readlink "$shome/bin/namerctl")" | cut -d- -f2)"

  jq -n \
    --arg namerd "$ver_namerd" \
    --arg namerctl "$ver_namerctl" \
    '{namerd: $namerd, namerctl: $namerctl}'
}

version "$@"
